version: '3.0'

services:
  vacancies.api:
    image: ghcr.io/fominykhartur/backend-vacancies-test-api/backend-vacancies-test-api:develop
    container_name: vacancies-api
    ports:
      - 3000:3000
    links:
      - postgres
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=vacancies
      - POSTGRES_PASSWORD=postgres
      - HOSTNAME=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
