version: '3.0'

services:
  vacancies.api:
    image: ghcr.io/fominykhartur/backend-vacancies-test-api/backend-vacancies-test-api:develop
    container_name: vacancies-api
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: 'vacancies'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1488'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
